# Form implementation generated from reading ui file 'ChangeMetadataFormDesignUi.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ChangeMetadataFormDesign(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 280)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(70, 0, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.FileChoseChangeMetadataButton = QtWidgets.QPushButton(parent=Form)
        self.FileChoseChangeMetadataButton.setGeometry(QtCore.QRect(10, 30, 381, 28))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.FileChoseChangeMetadataButton.setFont(font)
        self.FileChoseChangeMetadataButton.setObjectName("FileChoseChangeMetadataButton")
        self.PixmapChangeMetadataLabel = QtWidgets.QLabel(parent=Form)
        self.PixmapChangeMetadataLabel.setGeometry(QtCore.QRect(20, 120, 141, 141))
        self.PixmapChangeMetadataLabel.setText("")
        self.PixmapChangeMetadataLabel.setObjectName("PixmapChangeMetadataLabel")
        self.FieldChangeMetadataComboBox = QtWidgets.QComboBox(parent=Form)
        self.FieldChangeMetadataComboBox.setGeometry(QtCore.QRect(10, 80, 151, 22))
        self.FieldChangeMetadataComboBox.setObjectName("FieldChangeMetadataComboBox")
        self.ValueChangeMetadataLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.ValueChangeMetadataLineEdit.setGeometry(QtCore.QRect(170, 80, 221, 22))
        self.ValueChangeMetadataLineEdit.setText("")
        self.ValueChangeMetadataLineEdit.setObjectName("ValueChangeMetadataLineEdit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(200, 60, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ImagePathChangeMetadataButton = QtWidgets.QPushButton(parent=Form)
        self.ImagePathChangeMetadataButton.setGeometry(QtCore.QRect(170, 110, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.ImagePathChangeMetadataButton.setFont(font)
        self.ImagePathChangeMetadataButton.setObjectName("ImagePathChangeMetadataButton")
        self.WarningChangeMetadataLabel = QtWidgets.QLabel(parent=Form)
        self.WarningChangeMetadataLabel.setGeometry(QtCore.QRect(250, 200, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.WarningChangeMetadataLabel.setFont(font)
        self.WarningChangeMetadataLabel.setObjectName("WarningChangeMetadataLabel")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(180, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.WarningImageChangeMetadataLabel = QtWidgets.QLabel(parent=Form)
        self.WarningImageChangeMetadataLabel.setGeometry(QtCore.QRect(250, 170, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.WarningImageChangeMetadataLabel.setFont(font)
        self.WarningImageChangeMetadataLabel.setObjectName("WarningImageChangeMetadataLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ИЗМЕНЕНИЕ МЕТАДАТЫ mp3 ФАЙЛОВ"))
        self.FileChoseChangeMetadataButton.setText(_translate("Form", "Выберите файл"))
        self.label_3.setText(_translate("Form", "Название поля метадаты"))
        self.label_4.setText(_translate("Form", "Значение поля метадаты"))
        self.ImagePathChangeMetadataButton.setText(_translate("Form", "Изменить картинку\n"
"обложки альбома"))
        self.WarningChangeMetadataLabel.setText(_translate("Form", "ОШИБКА"))
        self.label_6.setText(_translate("Form", "СОХРАНЕНИЕ ПРОИСХОДИТ\n"
"        АВТОМАТИЧЕСКИ"))
        self.WarningImageChangeMetadataLabel.setText(_translate("Form", "ОШИБКА"))
