# the code is assembled from different parts from different .ui files
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class CreatePlaylistDesign(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(326, 357)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(80, 0, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CreatePlaylistNameLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.CreatePlaylistNameLineEdit.setGeometry(QtCore.QRect(10, 80, 301, 22))
        self.CreatePlaylistNameLineEdit.setObjectName("CreatePlaylistNameLineEdit")
        self.CreatePlaylistChooseFileButton = QtWidgets.QPushButton(parent=Form)
        self.CreatePlaylistChooseFileButton.setGeometry(QtCore.QRect(70, 110, 231, 28))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CreatePlaylistChooseFileButton.setFont(font)
        self.CreatePlaylistChooseFileButton.setObjectName("CreatePlaylistChooseFileButton")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.CreatePlaylistPathLabel = QtWidgets.QLabel(parent=Form)
        self.CreatePlaylistPathLabel.setGeometry(QtCore.QRect(20, 140, 281, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(6)
        self.CreatePlaylistPathLabel.setFont(font)
        self.CreatePlaylistPathLabel.setObjectName("CreatePlaylistPathLabel")
        self.CreatePlaylistImageLabel = QtWidgets.QLabel(parent=Form)
        self.CreatePlaylistImageLabel.setGeometry(QtCore.QRect(20, 190, 131, 131))
        self.CreatePlaylistImageLabel.setObjectName("CreatePlaylistImageLabel")
        self.CreatePlaylistCreateButton = QtWidgets.QPushButton(parent=Form)
        self.CreatePlaylistCreateButton.setGeometry(QtCore.QRect(170, 180, 131, 141))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.CreatePlaylistCreateButton.setFont(font)
        self.CreatePlaylistCreateButton.setObjectName("CreatePlaylistCreateButton")
        self.WarningPlaylistNameLabel = QtWidgets.QLabel(parent=Form)
        self.WarningPlaylistNameLabel.setGeometry(QtCore.QRect(10, 330, 311, 16))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        self.WarningPlaylistNameLabel.setFont(font)
        self.WarningPlaylistNameLabel.setObjectName("WarningPlaylistNameLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "СОЗДАТЬ ПЛЕЙЛИСТ"))
        self.label_2.setText(_translate("Form", "Название плейлиста"))
        self.CreatePlaylistChooseFileButton.setText(_translate("Form", "Выбрать файл"))
        self.label_3.setText(_translate("Form", "Обложка"))
        self.CreatePlaylistPathLabel.setText(_translate("Form", "Сдесь появится путь к файлу с изображением"))
        self.CreatePlaylistImageLabel.setText(_translate("Form", "Сдесь появится\n"
                                                                 " изображение\n"
                                                                 " для обложки"))
        self.CreatePlaylistCreateButton.setText(_translate("Form", "Создать"))
        self.WarningPlaylistNameLabel.setText(_translate("Form", "ПЛЕЙЛИСТ С ТАКИМ НАЗВАНИЕМ УЖЕ СУЩЕСТВУЕТ"))